# Payment servisi için Node.js 18 Alpine imajını kullan
FROM node:18-alpine

# Çalışma dizinini /app olarak ayarla
WORKDIR /app

# Package dosyalarını kopyala
COPY package*.json ./
COPY prisma ./prisma/

# Bağımlılıkları yükle
RUN npm install  --legacy-peer-deps

# TypeScript kaynak kodlarını kopyala
COPY . .

# TypeScript'i derle
RUN npm run build

# Prisma client'ı oluştur
RUN npx prisma generate

# Payment servisini 3000 portunda çalıştır
EXPOSE 3000

# Servisi başlat
CMD ["npm", "start"]
